DROP TABLE `clientes`
CREATE TABLE `productos` ( `CÓDIGOARTÍCULO` varchar(30) DEFAULT NULL, `SECCIÓN` varchar(30) DEFAULT NULL, `NOMBREARTÍCULO` varchar(30) DEFAULT NULL, `PRECIO` double DEFAULT NULL, `FECHA` varchar(30) DEFAULT NULL, `IMPORTADO` varchar(30) DEFAULT NULL, `PAÍSDEORIGEN` varchar(30) DEFAULT NULL );
SELECT * FROM `productos`
CREATE TABLE `clientes` ( `CÓDIGOCLIENTE` varchar(30) DEFAULT NULL, `EMPRESA` varchar(30) DEFAULT NULL, `DIRECCIÓN` varchar(30) DEFAULT NULL, `POBLACIÓN` varchar(30) DEFAULT NULL, `TELÉFONO` varchar(30) DEFAULT NULL, `RESPONSABLE` varchar(30) DEFAULT NULL );
SELECT * FROM `productos`
SELECT * FROM `clientes`