CREATE DATABASE IF NOT EXIST videoClub;
USE videoClub;
CREATE TABLE clientes(
    id INT(11) NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(200) DEFAULT NULL,
    apellido VARCHAR(200) DEFAULT NULL, 
    PRIMARY KEY(id)
);

CREATE TABLE videos(
    id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(200) DEFAULT NULL,
    director VARCHAR(200) DEFAULT NULL,
    cli_id INT(11) DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT video_fk FOREIGN KEY(cli_id) 
    REFERENCES clientes(id)
);